repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0
  hooks:
    - id: terraform_fmt
      stages: [commit]
    - id: terraform_validate
      stages: [commit]
    - id: terraform_tflint
      stages: [commit]
    - id: terraform_docs
      stages: [commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: end-of-file-fixer
      stages: [commit]
    - id: trailing-whitespace
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
      stages: [commit]
